- hosts: all
  sudo: true
  vars:
    php_ppa: php5
    php_packages:
      - { name: pear, package: php-pear }
      - { name: dev, package: php5-dev }
      - { name: fpm, package: php5-fpm }
      - { name: gd, package: php5-gd }
      - { name: imagick, package: php5-imagick }
      - { name: intl, package: php5-intl }
      - { name: memcached, package: php5-memcached }
      - { name: mongo, package: php5-mongo }
      - { name: mysqlnd, package: php5-mysqlnd }
      - { name: xdebug, package: php5-xdebug }
    php_extensions:
      - { name: v8js, package: pecl.php.net/v8js-0.4.1 }
    node_modules:
      - { name: bower }
      - { name: grunt-cli }
      - { name: gulp }
    project_name: symfony
    project_type: symfony # symfony|wordpress
    project_hostnames: symfony.dev
    doc_root: /var/www
  roles:
      - php5-common
      - php5-cli
      - curl
      - composer
      - mailcatcher
      - nodejs
      - node-common
      - nginx
  tasks:
    - name: Add mongodb repository key
      apt_key: keyserver=keyserver.ubuntu.com id=EA312927

    - name: update apt cache
      apt: update_cache=yes

    - name: Add PHP 5.6 repository
      apt_repository: repo='ppa:ondrej/php5-5.6' state=present

    - name: Add mongodb repository
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - ant
        - dos2unix
        - git
        - memcached
        - mysql-client
        - mysql-server
        - mongodb-org
        - php5

    - name: absent packages
      apt: name={{ item }} state=absent
      with_items:
        - apache2
