- hosts: all
  sudo: true
  vars:
    php_ppa: php5
    php_packages:
      - { name: dev, package: php5-dev }
  roles:
        - php5-common
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Add mongodb repository key
      apt_key: keyserver=keyserver.ubuntu.com id=EA312927
    - name: Add PHP 5.6 repository
      apt_repository: repo='ppa:ondrej/php5-5.6' state=present
    - name: Add mongodb repository
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - ant
        - dos2unix
        - git
        - memcached
        - mysql-client
        - mysql-server
        - mongodb-org
        - nginx
        - php5
        - php5-fpm
        - php5-gd
        - php5-imagick
        - php5-intl
        - php5-memcached
        - php5-mongo
        - php5-mysqlnd
        - php5-xdebug
    - name: absent packages
      apt: name={{ item }} state=absent
      with_items:
        - apache2
