---
- name: Install MongoDB
  sudo: yes
  apt:  pkg=mongodb state=latest

- name: Allow access to MongoDB from anywhere
  sudo: yes
  lineinfile: dest=/etc/mongodb.conf regexp="^bind_ip" line="#bind_ip = 127.0.0.1"
  notify: restart mongodb

- name: Add mongodb repository key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927

- name: Add mongodb repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: update apt cache
  apt: update_cache=yes
  
- name: Install MongoDB
  sudo: yes
  apt:  pkg=mongodb-org state=latest
