---
# wkhtmltopdf

- name: wkhtmltopdf | Install xfonts MongoDB
  sudo: yes
  apt:  pkg=xfonts-75dpi

- name: wkhtmltopdf | Download package
  command: wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_linux-trusty-amd64.deb

- name: wkhtmltopdf | Install package
  sudo: yes
  command: dpkg -i wkhtmltox-0.12.2_linux-trusty-amd64.deb
